config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  
  resources :users, only:[:show]
  
  resources :listings
  
  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end
  
  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get "manage-listing/:id/description" => "listings#description", as:"manage_listing_description"
  get "manage-listing/:id/address" => "listings#address", as:"manage_listing_address"
  get "manage-listing/:id/price" => "listings#price", as:"manage_listing_price"
  get "manage-listing/:id/photos" => "listings#photos", as:"manage_listing_photos"
  get "manage-listing/:id/calendar" => "listings#calendar", as:"manage_listing_calendar"
  get "manage-listing/:id/bankaccount" => "listings#bankaccount", as:"manage_listing_bankaccount"
  get "manage-listing/:id/publish" => "listings#publish", as:"manage_listing_publish"
  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :photos, dependent: :destroy
  
  # validates :address, presence:true
  # validates :service_type, presence:true
  # validates :price_setting, presence:true
  
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :listing
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  has_many :listings
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   
      user.image = "http://graph.facebook.com/#{auth.uid}/picture?type=large"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show, :update, :basics, :description, :address, :price, :photos, :calendar, :bankaccount,:publish]
  
  def index
    @listings = current_user.listings  #現在のユーザーが持っている全てのリスティングを入れてください。
  end

  def show
    @photos = @listing.photos
  end

  def new
    @listing = current_user.listings.build
  end

  def create
    #parameterとともに現在のユーザーのリスティングを作成
    @listing = current_user.listings.build(listing_params)
    if @listing.save
      redirect_to manage_listing_basics_path(@listing), notice: "リスティングを作成・保存をしました"
    else
      render new_listing_path, notice: "リスティングを作成・保存出来ませんでした"
    end
  end

  def edit
  end

  def update
    @listing.update(listing_params)
    if @listing
      redirect_to :back, notice:"更新できました。"
    end
  end
  
  def basics
  end
  
  def description
  end
  
  def address
  end
  
  def price
  end
  
  def photos
    @photo = Photo.new
  end
  
  def calendar
  end
  
  def bankaccount
  end
  
  def publish
  end
  
  private
  
  def set_listing
      @listing = Listing.find(params[:id])
  end
  
  def listing_params
    params.require(:listing).permit(:plan_title, :plan_detail, :shop_info, :acceptable, :plan_time, :guide_detail, :cancel_policy, :capacity, :address, :service_type, :price_setting, :use_language, :residentcountry, :residentcity, :use_language_level, :language_2, :language_level_2, :resident_years, :favorite_topic, :self_praise, :current_situation, :my_goal)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
    def create
        @photo = Photo.new(photo_params)
        if @photo.save
            render json: { message: "success", photoId: @photo.id }, status: 200
        else
            render json: { error: @photo.errors.full_messages.join(", ") }, status: 400
        end
    end

    def destroy
        @photo = Photo.find(params[:id])
        if @photo.destroy
            render json: { message: "file deleted from server" }
        else
            render json: { message: @photo.errors.full_messages.join(", ") }
        end
    end

    def list
        listing = Listing.find(params[:listing_id])

        photos = []
        Photo.where(listing_id: listing.id).each do |photo|
            new_photo = {
                id: photo.id,
                name: photo.image_file_name,
                size: photo.image_file_size,
                src: photo.image(:thumb)
            }
            photos.push(new_photo)
        end
        render json: { images: photos }
    end

    private
    def photo_params
        params.require(:photo).permit(:image,:listing_id,:listing_image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  def edit
  end
  
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
  
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :age, :sex, :nationality, :resident_country, :resident_city, :job, :language_1, :description])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number, :age, :sex, :nationality, :resident_country, :resident_city, :job, :language_1, :description])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def controller?(controller)
		controller.include?(params[:controller])#引数が現在のコントローラーに含まれていたらtrueを返す
	end

	def action?(action)
		action.include?(params[:action])#引数が現在のアクションに含まれていたらtrueを返す
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/homes/index.html.erb
<script type="text/javascript">
    $(function(){
        $(".navbar").removeClass("navbar-devise");
        $(".navbar").addClass("navbar-default");
    });
</script>

<div class="jumbotron image-space">
　<%= render partial: "partial/navbar" %>
　<div class="container">
　    <div class="row">
　        <div class="col-md-8 col-md-offset-2 text-center">
　            <h1>10年後、出会った人の顔が<br class="br-sp">思い出される旅にしよう!</h1>
　            <h4><span class="top-page-title">その土地の人だけが知っている美味しいお店で、気軽な出会いを楽しみました。</span></h4>
　        </div>
　    </div>
　</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tabitomo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<!-- flashにメッセージがある時 -->
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |f| %>
            <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
            toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
    </script>
<% end %>

</body>
</html>

app/views/listings/address.html.erb
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">住所の編集</span>
                </div>
            </div>

            <div class="panel-body">          

                <%= form_for @listing do |f| %>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>住所</label>
                                <%= f.text_field :address, placeholder: "例: 東京都新宿区西新宿3丁目234-3", class: "form-control", required: "true" %>
                            </div>
                        </div>
                    </div>
                    
                    <h4>My Google Maps</h4>
                    <div id="map"></div>

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>



<script>
  function initMap() {
    var uluru = {lat: <%=@listing.latitude %>, lng: <%=@listing.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 14,
      center: uluru
    });
    var marker = new google.maps.Marker({
      position: uluru,
      map: map
    });
  }
</script>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBUH0GAPxrsmJwe--8-vQZcokwg2N7GX9o&callback=initMap">
</script>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/index.html.erb
<%= render 'partial/navbar' %>

<div class="container"> 
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:18px;">リスティング一覧</span>
                </div>
            </div>
            <ul class="ul-unstyled">
                <% @listings.each do |listing| %>
                    <li class="panel-body">
                        <div class="row-table">
                            <div class="col-sm-2 col-md-2">
                                <div class="panel-list-img text-center">
                                    <%= image_tag listing.photos[0].image.url(:medium) if listing.photos.length > 0  %>    
                                </div> 
                            </div>

                            <div class="col-sm-7 col-md-7">
                                <span class="listing-title"><%= listing.service_type %></span>
                                <p>作成日:<%= listing.created_at %></p>
                                <p>更新日:<%= listing.updated_at %></p>
                            </div>
                            
                            <div class="col-sm-3 col-md-3">
                                <%= link_to "残り5ステップ", manage_listing_basics_path(listing), class: "btn btn-primary pull-right" %>
                            </div>
                        </div>
                    </li>
                <% end %>               
            </ul>     
        </div>
        
    </div>
</div>

app/views/listings/show.html.erb
<%= render 'partial/navbar' %>

<!-- ジャンボトロン -->
<div class="jumbotron row-space-0">
    <div class="top-photo-image">
        <% if @photos %>             
            <% @photos.each_with_index do |photo,i| %>
               <% if i == 0 %>
                  <%= image_tag photo.image.url() %>
               <% end %>
            <% end %>   
        <% end %>
    </div>
</div>

<!-- サマリー -->
<div class="container-fluid container-listing-show">
    <div class="container">
        <div class="listing-summary row-space-3 row-space-top-3">
            <div class="row">
                <div class="col-md-3 text-center row-space-2">
                    <%= link_to user_path(@listing.user) do %>
                        <%= image_tag @listing.user.image,class:"img-circle profile-2" %>
                    <% end %>
                    <h5><%= @listing.user.name %></h5>
                </div>
                <div class="col-md-6">
                    <div class="listing-title" style="font-size:24px;">
                        
                    </div>
                    <div class="row row-space-top-4">
                        <div class="col-sm-3 col-xs-3 text-center">
                            <i class="fa fa-home fa-3x"></i>
                            <h5><%= @listing.residentcountry %></h5>
                        </div>
                        <div class="col-sm-3 col-xs-3 text-center">
                            <i class="fa fa-linux fa-3x" aria-hidden="true"></i>
                            <h5><%= @listing.residentcity %></h5>
                        </div>
                        <div class="col-sm-3 col-xs-3 text-center">
                            <i class="fa fa-clock-o fa-3x" aria-hidden="true"></i>
                            <h5><%= @listing.use_language %></h5>
                        </div>
                        <div class="col-sm-3 col-xs-3 text-center">
                            <i class="fa fa-bug fa-3x" aria-hidden="true"></i>
                            <h5><%= @listing.use_language_level %></h5>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="panel panel-default panel-show">
                        <div class="panel-heading">
                                <span style="font-size:16px;"><%= @listing.price_setting %>円（一サービスあたり）</span>
                        </div>
                        
                        <div class="panel-body panel-real">         
                            <%= form_for @listing, :html => { multipart: true } do |f| %>                                   
                                <div class="actions text-center">
                                    <%= f.submit "この日程で予約する", class: "btn btn-danger btn-wide" %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- メインコンテント -->
<div class="show-main">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 s-page">
                <div class="self-info-part">
                    <h2 class="row-space-3 double-line"><span class="plan-title"><%= @listing.plan_title %></span></h2>
                    <br>
                    <h4><span class="title-line"><%= fa_icon "plane", text: "プランの詳細", left: true %></span></h4>
                    <p class="description-space"><%= @listing.plan_detail %></p>
                    <p class="description-space"><span class="meethere"><%= link_to "Click here! こんなお店でお会いしましょう。", @listing.shop_info %></span></p>
                    
                    <h4><span class="title-line"><%= fa_icon "plane", text: "イメージ画像", left: true %></span></h4>
                      <ul class="bxslider">
                          <% if @photos %>             
                            <% @photos.each do |photo| %>
                              <li class="item <%= 'active' if photo.id == @photos[0].id %>">   
                                  <%= image_tag photo.image.url() %>
                              </li>
                            <% end %>   
                          <% end %>
                        </ul>
                    <br>
                    <h4><span class="title-line"><%= fa_icon "plane", text: "説明", left: true %></span></h4>
                    <div class="description_table">
                        <table class="table table-bordered">
                          <tbody>
                              <% if @listing.guide_detail %>      
                                  <tr>
                                      <td class="table-title">ガイド詳細</td>
                                      <td class="table-detail"><%= @listing.guide_detail %>時間</td>
                                  </tr>
                              <% end %>
                              <tr>
                                  <td class="table-title">最大受け入れ人数</td>
                                  <td class="table-detail"><%= @listing.acceptable %>名</td>
                              </tr>
                              <tr>
                                  <td class="table-title">所要時間</td>
                                  <td class="table-detail"><%= @listing.plan_time %>時間</td>
                              </tr>
                              <tr>
                                  <td class="table-title">私ができること、できないこと</td>
                                  <td class="table-detail"><%= @listing.capacity %></td>
                              </tr>
                              <tr>
                                  <td class="table-title">キャンセルポリシー</td>
                                  <td class="table-detail"><%= @listing.cancel_policy %>時間</td>
                              </tr>
                          </tbody>
                        </table>
                    </div>
                    
                    <h4><span class="title-line"><%= fa_icon "plane", text: "待ち合わせ場所", left: true %></span></h4>
                    <div id="map"></div>
                    
                    
                    <div class="self-intro">
                        <h4><span class="title-line"><%= fa_icon "plane", text: "自己紹介", left: true %></span></h4>
                        <div class="row">
                            <div class="col-sm-2 hidden-xs">
                                <%= link_to user_path(@listing.user) do %>
                                    <%= image_tag @listing.user.image,class:"img-circle profile-2" %>
                                <% end %>
                            </div>
                            <div class="col-sm-6 hidden-xs">
                                <p class="arrow_box">私はこんな人です。</p>
                            </div>
                        </div>
                        <div class="intro-content">
                            <h5><strong>私が得意な話</strong></h5>
                            <p class="self-detail"><%= @listing.favorite_topic %></p>
                            
                            <h5><strong>私の自慢</strong></h5>
                            <p class="self-detail"><%= @listing.self_praise %></p>
                            
                            <h5><strong>私の現在の状況</strong></h5>
                            <p class="self-detail"><%= @listing.current_situation %></p>
                            
                            <h5><strong>私が目指すもの</strong></h5>
                            <p class="self-detail"><%= @listing.my_goal %></p>
                        </div><!--intro-content-->
                    </div><!--self-intro-->
                </div><!--self-info-part-->
                <div class="customer-comment-part">
                    
                </div><!--customer-comment-part-->
            </div>
        </div>  
    </div>
</div>



<script type="text/javascript">
    $('.bxslider').bxSlider({
    mode: 'fade',
    auto: true,
    autoControls: true,
    pause: 5000
    });
</script>

<script type="text/javascript">
  function initMap() {
    var uluru = {lat: <%=@listing.latitude %>, lng: <%=@listing.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 14,
      center: uluru
    });
    var marker = new google.maps.Marker({
      position: uluru,
      map: map
    });
  }
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBUH0GAPxrsmJwe--8-vQZcokwg2N7GX9o&callback=initMap">
</script>


<script>
$(window).on('load resize', function(){
     trimming('.top-photo-image');//ここにトリミングしたい枠の種類を書くだけ（枠のサイズが同じなら1つ書けばOK。）
})
function trimming ($photoBox) {    //Functionで機能をまとめ
    jQuery($photoBox).each(function(){
        var box = jQuery(this);
        var i = jQuery('img',this);
        var box_w =$(box).width();
        var box_h =$(box).height();
        var i_w =$(i).width();
        var i_h =$(i).height();
        var i_par =i_w / i_h; //画像の縦横比
        var box_par =box_w / box_h; //画像を包むボックスの縦横比
       //画像の縦横比と枠の縦横比を比べて分岐させ違うトリミングをする
        if (i_par > box_par) { //画像が枠より横長の場合高さ100%で幅左右を切る
            $(i).css({
                "width": "auto",
                "height":"100%"
            });
        }else{
            $(i).css({//画像が枠より縦長または同じの場合幅100%にして高さの上下を切る
                "width": "100%",
                "height":"auto"
            });
        }
    });
}
</script>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/partial/_deviseErrorMsg.html.erb
<!-- deviseにエラーがある場合 -->
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>');
		<% end %>
	</script>
<% end %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-devise">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brand</a>   
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
              <!-- ログインしていない時 -->
          <% if (!user_signed_in?) %>
              <li><a href="#">利用の流れ</a></li>
              <li><%= link_to "アカウント作成", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <!-- ログインしている時 -->
          <% else %>
              <li><%= link_to "TABITOMO登録", new_listing_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <% if current_user.provider %>
                    <!--認証ログインをしている時-->
                    <%= image_tag current_user.image, class:"img-circle profile-0" %>
                    <%= current_user.name %>
                  <% else %>
                    <%= current_user.email %>
                  <% end %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "プロフィール", user_path(current_user) %></li>
                  <li><%= link_to "基本情報編集", edit_user_registration_path %></li>
                  <li><%= link_to "リスティング表示", listing_path(current_user) %></li>
                  <li><%= link_to "リスティング管理", listings_path(current_user) %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>          
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partial/_verticalnavbar.html.erb
<div class="panel panel-success">
  <!-- Default panel contents -->
  <div class="verticalnav panel-heading"><strong>表示画面へ</strong></div>
  <!-- List group -->
  <ul class="verticalnav list-group">
    <li class="display list-group-item">
      <%= link_to "確認する", listing_path(@listing) %>
    </li>
  </ul>
</div>

<div class="panel panel-warning">
  <!-- Default panel contents -->
  <div class="verticalnav panel-heading"><strong>表示の編集</strong></div>
  <!-- List group -->
  <ul class="verticalnav list-group">
    <li class="<%= 'active' if controller?("listings") && action?("basics") %> list-group-item">
      <%= link_to "基本事項", manage_listing_basics_path(@listing) %>
    </li>
    <li class="<%= "active" if controller?("listings") && action?("description") %> list-group-item">
      <%= link_to "リスティングの内容", manage_listing_description_path(@listing) %>
    </li>
    <li class="<%= "active" if controller?("listings") && action?("address") %> list-group-item">
      <%= link_to "住所情報", manage_listing_address_path(@listing) %>
    </li>
    <li class="<%= "active" if controller?("listings") && action?("price") %> list-group-item">
      <%= link_to "料金設定", manage_listing_price_path(@listing) %>
    </li>
    <li class="<%= "active" if controller?("listings") && action?("photos") %> list-group-item">
      <%= link_to "イメージ写真の設定", manage_listing_photos_path(@listing), "data-turbolinks": "false" %>
    </li>
    <li class="<%= "active" if controller?("listings") && action?("calendar") %> list-group-item">
      <%= link_to "予約画面の設定", manage_listing_calendar_path(@listing) %>
    </li>
    <li class="<%= "active" if controller?("listings") && action?("bankaccount") %> list-group-item">
      <%= link_to "受取口座情報", manage_listing_bankaccount_path(@listing) %>
    </li>
    <li class="<%= "active" if controller?("listings") && action?("publish") %> list-group-item">
      <%= link_to "公開する", manage_listing_publish_path(@listing) %>
    </li>
  </ul>
</div>

app/views/users/show.html.erb
<%= render 'partial/navbar' %>

<!-- 認証チェックマーク -->
<script type="text/javascript">
	$(function(){
		<% if !@user.email.blank? %>
			$("#ver-email").attr('class','vertification-checked');
		<% end %>

		<% if !@user.phone_number.blank? %>
			$("#ver-tel").attr('class','vertification-checked');
		<% end %>

		<% if @user.provider == "facebook" %>
			$("#ver-facebook").attr('class','vertification-checked');
		<% end %>
	});
</script>


<section>
	<div class="container">
		<div class="row content">
			<div class="col-md-8 col-sm-8 col-xs-12">
				<div class="profile-card">
					<div class="row">
                      <div class="col-md-4 col-xs-12 col-sm-5 col-lg-4">
	                      <div class="imagearea">
	                          <%= image_tag @user.image, class: "img-responsive profile-full img-circle" %>
	                      </div><!--imagearea-->
                      </div>
                      <div class="col-md-8 col-xs-12 col-sm-7 col-lg-8">
                          <div class="container name-line">
                            <h2><%= @user.name %></h2>
                          </div>
                          <div class="simple-info">
                          	<ul>
                          		<li><span class="glyphicon glyphicon-map-marker"></span><%= @user.nationality %></li>
                          		<li><span class="glyphicon glyphicon-briefcase"></span><%= @user.job %></li>
                          	</ul>
                          </div>
                      </div>
                  </div><!--row-->
				</div><!--profile-card-->
				<div class="profile-info panel panel-default">
		            <div class="panel-heading">
		              <h3 class="panel-title text-center">プロフィール情報</h3>
		            </div>
		            <div class="panel-body">
						<div class="profile-details">
							<table class="table table table-hover table-user-information">
			                    <tbody>
			                      <tr>
			                        <td><span class="glyphicon glyphicon-pencil"></span>NAME</td>
			                        <td>:<%= @user.name %></td>
			                      </tr>
			                      <tr>
			                        <td><span class="glyphicon glyphicon-user"></span>GENDER</td>
			                        <td>:<%= @user.sex %></td>
			                      </tr>
			                      <tr>
			                        <td><span class="glyphicon glyphicon-th"></span>AGE</td>
							        <td>:<%= @user.age %>歳</td> 
			                      </tr>
			                      <tr>
			                        <td><span class="glyphicon glyphicon-map-marker"></span>COUNTRY</td>
							        <td>:<%= @user.nationality %></td>  
			                      </tr>
			                      <tr>
			                        <td><span class="glyphicon glyphicon-briefcase"></span>OCCUPATION</td>
							        <td>:<%= @user.job %></td>
			                      </tr>
			                      <tr>
			                        <td><span class="glyphicon glyphicon-phone"></span> MOBILE</td>
						            <td>:<%= @user.phone_number %></td> 
			                      </tr>
			                      <tr>
			                        <td><span class="glyphicon glyphicon-envelope"></span>EMAIL</td>
						            <td>:<%= @user.email %></td>
			                      </tr>
			                      <tr>
			                        <td><span class="glyphicon glyphicon-comment"></span>自己紹介</td>
						            <td>:<%= @user.description %></td>
			                      </tr>
			                    </tbody>
			                  </table>
						</div><!--profile-details-->
					</div><!--panel-body-->
				</div><!--profile-info-->
			</div><!--col-md-8 col-sm-8 col-xs-12-->
			<div class="col-md-4 col-sm-4 col-xs-12">
				<div class="panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading">Panel heading</div>
				  <!-- List group -->
				  <ul class="list-group">
				    <li class="list-group-item">
						<%= link_to "プロフィール", user_path(current_user), class: "glyphicon glyphicon-home" %>
					</li>
					<li class="list-group-item">
						<%= link_to "プロフィール編集", edit_user_registration_path(current_user), class: "glyphicon glyphicon-user" %>
					</li>
					<li class="list-group-item">
						<%= link_to "リスティング作成", new_listing_path, class: "glyphicon glyphicon-user" %>
					</li>
				  </ul>
				  <div class="verifications hidden-xs hidden-sm">
						<p><span class="glyphicon glyphicon-ok"></span>認証済みID</p>
						<ul>
							<li id="ver-email">メールアドレス</li>
							<li id="ver-tel">電話番号</li>
							<li id="ver-facebook">Facebook</li>
						</ul>
					</div>
				</div>
			</div>
		</div><!--row-->
	</div><!--container-->
</section><!--section close-->